### ISSUE TITLE
Unhandled Exception: System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by dhx10000** [Microsoft/fasttrack-smat-workbook-generator#2]
On both 1.0.0 and 1.0.1, when I run this command: smatwb -s "C:\" I receive the following error:

Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.FastTrack.SMATWorkbookGenerator.Program.ValidateArguments(Args arguments) in C:\github\fasttrack-smat-workbook-generator\smat-workbook-generator\Program.cs:line 89
   at Microsoft.FastTrack.SMATWorkbookGenerator.Program.Main(String[] args) in C:\github\fasttrack-smat-workbook-generator\smat-workbook-generator\Program.cs:line 52

**Comment by patrick-rodgers** [comment]
the s parameter should be the path to your input files and I don't think c: is a valid path. What is the folder path where you are running the tool (where the exe sits) and where your SMAT output sits?

**Comment by dhx10000** [comment]
thank you, I had to specify the output folder correctly and ensure the SummaryReport.csv was at the root of the directory specified in the s command

**Comment by patrick-rodgers** [comment]
Great! Glad you are unblocked and thanks for using the tool. Going to close this as answered - let us know if you run into any other issues. Thanks!
